# Generated by Django 5.0.7 on 2024-08-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='price_per_night',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='place',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='place',
            name='available_to',
        ),
        migrations.AddField(
            model_name='place',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='places/pictures/'),
        ),
    ]
